mysite_bad2/flights/urls.py
from django.urls import path
from .views import hello, airports, flight, date_filter

app_name = 'flight'
urlpatterns = [
    # path('hello', hello),
    path('', airports, name='airports'),
    path('<int:flight_id>', flight, name='flight'),
    path('date-filter/', date_filter, name='date_filter')
]

mysite_bad2/flights/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Flight, Airport


# Create your views here.
def hello(request):
    return HttpResponse('hello')


def airports(request):
    f = Airport.objects.all()
    context = {
        'airports': f
    }
    return render(request, 'index.html', context)


def flight(request, flight_id):
    #f = Flight.objects.get(pk=flight_id)
    f = get_object_or_404(Flight, pk=flight_id)
    context = {
        'flight': f
    }
    return render(request, 'flight.html', context)

def date_filter(request):
    start_date = request.GET.get('start_date')
    f = None
    if start_date:
        f = Flight.object.filter(created__gte = start_date)
    contex = {
        'flights': f,
        'date': start_date
    }
    return render(request, 'date_filter.html', context)

mysite_bad2/flights/templates/date_filter.html
{% extends 'base.html' %}

{% block title %} Фильтр по дате {% endblock %}

{% block body %}
    <h1>Полеты</h1>
    <form method="GET" action="{% url 'flight:date_filter'%}">
        <label> Фильтрация по дате</label>
        <input type="date" name="start_date" id="start_date">
        <button type="submit"> Подтвердить </button>
    </form>
{% if date %}
    <
{% endblock %}

mysite_bad2/flights/templates/index.html
{% extends 'base.html' %}

{% block title %} Вылеты {% endblock %}

{% block body %}
    <h1>Полеты</h1>
    <form method="GET" action="{% url 'flight:date_filter'%}">
        <label> Фильтрация по дате</label>
        <input type="date" name="start_date" id="start_date">
        <button type="submit"> Подтвердить </button>
    </form>
    <ul>
        {% for airport in airports %}
        <p>{{ airport }}</p>
              {% for flight in airport.get_arrivals %}
                <li> <a href="{% url 'flight:flight' flight.id %}"> {{flight}} </a> </li>
              {% endfor %}
        <br>
        {% endfor %}
    </ul>
{% endblock %}