blog/app/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/post/urls.py
from django.urls import path
from .views import posts, postid, comments, date_filter

app_name = 'posts'
urlpatterns = [
    path('', posts, name='posts'),
    path('<int:post_id>', postid, name='postid'),
    path('', comments),
    path('date-filter/', date_filter, name='date_filter')
]

blog/forum/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    Topic = models.CharField(max_length=256, verbose_name='Тема')
    Text = models.TextField(verbose_name='Текст')

    def __str__(self):
        return self.Topic

    def get_comments(self):
        return self.post_comment.all()

class Comment(models.Model):
    text = models.TextField(verbose_name='Текст')
    post = models.ForeignKey(Post, related_name='post_comment', on_delete=models.CASCADE, verbose_name='Связанный пост')

    def __str__(self):
        return self.text

blog/post/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.
class Post(models.Model):
    postname = models.CharField(max_length=200, verbose_name='Тема поста')
    posttext = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(verbose_name='Время создания', default=now)

    def __str__(self):
        return f'subject: {self.postname} text: {self.posttext}'

    def get_comments(self):
        return self.comment_postcomment.all()


class Comments(models.Model):
    postcomm = models.ForeignKey(Post, verbose_name='Комментируемый пост', related_name='comment_postcomment', on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Комментарий')

    def __str__(self):
        return f'Текст комментария: {self.comment}'

blog/forum/views.py
from django.shortcuts import render
from .models import Post, Comment

# Create your views here.

blog/post/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Comments


# Create your views here.
def posts(request):
    f = Post.objects.all()
    # return HttpResponse(f)
    context = {
        'posts': f
    }
    return render(request, 'index.html', context)


def postid(request, post_id):
    f = get_object_or_404(Post, pk=post_id)
    context = {
        'postid': f
    }
    #return HttpResponse(f)
    return render(request, 'post.html', context)

def comments(request):
    f = Comments.objects.all()
    return HttpResponse(f)

def date_filter(request):
    start_date = request.GET.get('start_date')
    filter_type = request.GET.get('filter_type')
    f = None
    if start_date:
        if filter_type == 'gte':
            f = Post.objects.filter(created__gte=start_date)
        elif filter_type == 'lte':
            f = Post.objects.filter(created__lte=start_date)
    context = {
        'posts': f,
        'date': start_date
    }
    return render(request, 'date_filter.html', context)

blog/post/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block body%} {% endblock %}
</body>
</html>

blog/post/templates/date_filter.html
{% extends 'base.html' %}

{% block title %} Фильтр по дате {% endblock %}

{% block body %}
    <h1>Посты</h1>
    <form method="GET" action="{% url  'posts:date_filter'%}">
        <label>Фильтрация по дате</label>
        <input type="date" name="start_date" id="start_date">
        <button type="submit">Подтвердить</button>
    </form>

{% if date %}
    {% if filter_type == 'gte' %}
    <p>Посты начиная с {{date}}</p>
    {% endif %}

    {% if filter_type == 'lte' %}
    <p>Посты до {{date}}</p>
    {% endif %}

    <ul>
              {% for post in posts %}
                <li> <a href="{% url 'posts:postid' post.id %}"> {{post}} </a> </li>
              {% endfor %}
    </ul>
{%endif%}
{% endblock %}

blog/post/templates/index.html
{% extends 'base.html' %}

{% block title %} Блог {% endblock %}

{% block body %}
    <h1>Мой блог.</h1>
    <ul>
        {% for post in posts %}
        <li> <a href="{% url 'postid' post.id %}"> {{ post }} </a> </li>
            {% for comments in post.get_comments %}
        <a> {{ comments }} </a>
            {% endfor %}
        <br>
        {% endfor %}
    </ul>
{% endblock %}

blog/post/templates/post.html
{% extends 'base.html' %}

{% block title %} Пост {% endblock %}

{% block body %}
    <h1> Пост {{postid.id}}</h1>
    <h1> {{postid}}</h1>
        {% for comments in postid.get_comments %}
            <p>{{ comments }} </p>
        {% endfor %}
    <a href="{% url 'posts:posts'%}"> Вернуться назад </a>
{% endblock %}