mysite/api/urls.py
from rest_framework import routers
from .views import FlightViewset, PassengerViewset, FeedbackViewset, AirportViewset, SecurityViewset

flight_router = routers.DefaultRouter()
flight_router.register('flights', FlightViewset)
flight_router.register('passenger', PassengerViewset)
flight_router.register('feedback', FeedbackViewset)
flight_router.register('airport', AirportViewset)
flight_router.register('security', SecurityViewset)



urlpatterns = []
urlpatterns += flight_router.urls

mysite/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('flights.urls')),
    path('api/v1/', include('api.urls')),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(next_page='login'), name='logout')
]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/flights/urls.py
from django.urls import path
from .views import hello, airports, flight, date_filter, passanger


app_name = 'flights'
urlpatterns = [
    path('hello', hello),
    path('', airports, name='airports'),
    path('<int:flight_id>', flight, name='flight'),
    path('passanger/<str:slug>', passanger, name='passanger'),
    path('date-filter/', date_filter, name='date_filter')
]

mysite/flights/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User


class Airport(models.Model):
    name = models.CharField(max_length=60, verbose_name='Название')
    city = models.CharField(max_length=60, verbose_name='Город')
    image = models.ImageField(verbose_name='Фото', blank=True, null=True)

    def __str__(self):
        return f'Аэропорт {self.name} в городе {self.city}'

    def get_arrivals(self):
        return self.flight_destination.all()

    class Meta:
        verbose_name = 'Аэропорт'
        verbose_name_plural = 'Аэропорты'
        ordering = ('city', )


class Flight(models.Model):
    origin = models.ForeignKey(Airport, verbose_name='Точка отправления', related_name='flight_origin', on_delete=models.CASCADE, null=True)
    destination = models.ForeignKey(Airport, verbose_name='Точка прибытия', related_name='flight_destination', on_delete=models.CASCADE, null=True)
    duration = models.IntegerField(verbose_name='Длительность')
    created = models.DateTimeField(verbose_name='Время создания', default=now)

    def __str__(self):
        return f'Вылет из {self.origin} в {self.destination}. Длительность {self.duration} часов\n'
    class Meta:
        verbose_name = 'Вылет'
        verbose_name_plural = 'Вылеты'
        ordering = ('origin', 'duration')

class Passenger(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=60)
    second_name = models.CharField(verbose_name='Фамилия', max_length=60)
    flights = models.ManyToManyField(Flight, verbose_name='Вылеты', related_name='passanger_flights')
    slug = models.SlugField(verbose_name='ЧПУ', unique=True, blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.second_name}'

class Security(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=60)
    second_name = models.CharField(verbose_name='Фамилия', max_length=60)
    post = models.CharField(verbose_name='Должность', max_length=60)
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)


    class Meta:
        verbose_name = 'Сотрудник службы безопасности'
        verbose_name_plural = 'Сотрудники службы безопасности'
        ordering = ('name', 'second_name')

    def __str__(self):
        return f'{self.name} {self.second_name}'

mysite/flights/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Flight, Airport, Passenger, Security
from django.contrib.auth.decorators import login_required



# Create your views here.
def hello(request):
    #all_objs = Flight.objects.all()     #[1:3] можно сделать срез
    #first_objs = Flight.objects.first()
    #print(first_objs)
    #ordered_obj = Flight.objects.order_by('duration') #можно сделать с минусом для обратной сортировки
    #ordered_obj = Flight.objects.order_by('-duration').first()
    #print(ordered_obj)
    #get_obj = Flight.objects.get(id=1)

    #my_airport = Airport.objects.get(name='Пулково')
    #get_airports_flights = Flight.objects.filter(destination=my_airport)# или использовать id
    #print(get_airports_flights)

    #get_exclude_airports = Flight.objects.filter(origin=2).exclude(destination=1)
    #print(get_exclude_airports)

    #my_airport1 = Airport.objects.get(name='Пулково')
    #my_airport2 = Airport.objects.get(name='Хитроу')
    #f = Flight.objects.create(origin=my_airport1, destination=my_airport2, duration=2)
    #print(f)

    #f = Flight.objects.get(id=1)
    #f.duration = 200
    #f.save()
    #print(f)

    #Flight.objects.get(id=1).delete()
    """Airport.objects.bulk_create([
        Airport(name='Иваново', city='Иваново'),
        Airport(name='Внуково', city='Москва')
    ])"""
    #print(Airport.objects.get_or_create(name='Иваново', city='Иваново'))

    ##my_airport = Airport.objects.get(name='Шереметьево')
    ##get_airports_flight = Flight.objects.filter(origin=my_airport)
    ##print(get_airports_flight)
    ##get_passenger = Passenger.objects.filter(flights=get_airports_flight)


#    my_airport = Airport.objects.get(name='Шереметьево')
#    res = Passenger.objects.filter(flights__origin=my_airport)
#    print(res)
#    return HttpResponse('success')

#   my_airport = Airport.objects.get(name='Шереметьево')
#   res = Passenger.objects.filter(flights__origin=my_airport)[:3]
#    return HttpResponse(res)

    return HttpResponse('success')

@login_required()
def airports(request):
#    print(request.user.is_active)
#    print(request.user.is_staff)
#    print(request.user.is_superuser)
    print(request.user.is_authenticated)
    if request.user.is_authenticated:
        f = Airport.objects.all()
        context = {
            'airports': f
        }
        return render(request, 'index.html', context)
    else:
        return HttpResponse('Вам нужно авторизоваться')


def flight(request, flight_id):
    # f = Flight.objects.get(pk=flight_id)
    f = get_object_or_404(Flight, pk=flight_id)
    context = {
        'flight': f
    }
    #print(f.passanger_flights.all())
    #print(dir(f))
    return render(request, 'flight.html', context)

def date_filter(request):
    start_date = request.GET.get('start_date')
    filter_type = request.GET.get('filter_type')
    f = None
    if start_date:
        if filter_type == 'gte':
            f = Flight.objects.filter(created__gte = start_date)
        elif filter_type == 'lte':
            f = Flight.objects.filter(created__lte=start_date)
    context = {
        'flights': f,
        'date': start_date
    }
    return render(request, 'date_filter.html', context)

def passanger(request, slug):
    p = Passenger.objects.get(slug=slug)

    context = {
        'passanger' : p
    }
    return HttpResponse(p)

def security(request, slug):
    p = Security.objects.get(slug=slug)

    context = {
        'security' : p
    }
    return HttpResponse(p)

mysite/flights/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel = "stylesheet" type="text/css" href="{% static  'style.css' %}" />
</head>
<body>
    {% block body %} {% endblock %}
</body>
</html>

mysite/flights/templates/date_filter.html
{% extends 'base.html' %}

{% block title %} Фильтр по дате {% endblock %}

{% block body %}
    <h1>Полеты</h1>
    <form method="GET" action="{% url  'flights:date_filter'%}">
        <label>Фильтрация по дате</label>
        <input type="date" name="start_date" id="start_date">
        <fieldset>
            <input type="radio" id="gte" name="filter_type" value="gte" checked>
            <label>После указанной даты</label>
            <input type="radio" id="lte" name="filter_type" value="lte">
            <label>До указанной даты</label>
        </fieldset>
        <button type="submit">Подтвердить</button>
    </form>

{% if date %}
    {% if filter_type == 'gte' %}
    <p>Вылеты начиная с {{date}}</p>
    {% endif %}

    {% if filter_type == 'lte' %}
    <p>Вылеты до {{date}}</p>
    {% endif %}
    <ul>
              {% for flight in flights %}
                <li> <a href="{% url 'flights:flight' flight.id %}"> {{flight}} </a> </li>
              {% endfor %}
    </ul>
{%endif%}
{% endblock %}

mysite/flights/templates/flight.html
{% extends 'base.html' %}

{% block title %} Вылет {% endblock %}

{% block body %}
    <h1>Полет {{flight.id}}</h1>
    <h1>Полет {{flight}}</h1>
    <ul>
    {% for passanger in passangers %}
        <li> {{ passanger }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'flights:airports'%}">  Вернуться назад </a>
{% endblock %}

mysite/flights/templates/index.html
{% extends 'base.html' %}

{% block title %} Вылеты {% endblock %}

{% block body %}
    <!-- Коментарий --> 
    <h1>Полеты</h1>
    <form method="GET" action="{% url  'flights:date_filter'%}">
        <label>Фильтрация по дате</label>
        <input type="date" name="start_date" id="start_date">
        <fieldset>
            <input type="radio" id="gte" name="filter_type" value="gte" checked>
            <label>После указанной даты</label>
            <input type="radio" id="lte" name="filter_type" value="lte">
            <label>До указанной даты</label>
        </fieldset>
        <br>
        <button type="submit">Подтвердить</button>


    </form>

    <ul>
        {% for airport in airports %}
        {% if airport.image %}
            <img src="{{ airport.image.url }}" width='200' height='200'>
        {% endif %}
        <p>{{ airport }}</p>
              {% for flight in airport.get_arrivals %}
                <li> <a href="{% url 'flights:flight' flight.id %}"> {{flight}} </a> </li>
              {% endfor %}
        <br>
        {% endfor %}
    </ul>
{% endblock %}